### ISSUE TITLE
Script stops working due to changes in localapi

### ISSUE THREAD

**Issue by Luzl1** [mbugert/tailscale-polybar-rofi#1]
Since one of the last updates of tailscale the script stopped working.
If I call the local api manually (with the command from the script) I get the following error:

```
curl --silent --fail --unix-socket /run/tailscale/tailscaled.sock http://tailscale/localapi/v0/status
curl: (22) The requested URL returned error: 403
```
According to https://github.com/tailscale/tailscale/issues/6446 the command has to be changed into:

`curl --silent --fail --unix-socket /var/run/tailscale/tailscaled.sock http://local-tailscaled.sock/localapi/v0/status`

That worked for me.

**Comment by mbugert** [comment]
Thanks a lot for reporting! The URL is fixed.

I was still using the 1.30.0 tailscale client. In that release, both the old and the new URL are working.
